# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27

    - python: 3.4
      env: TOXENV=py34

    - python: 3.5
      env: TOXENV=py35

    - python: 3.6
      env: TOXENV=py36,mypy,flake8

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: python -m pip install -U tox

# command to run tests, e.g. python setup.py test
# Hell! Install pyside on py27, py34 needs about 30 minutes, depends on travis's
# network speed or remote download limits.
script: travis_wait 60 tox

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist
  user: starofrainnight
  password:
    secure: "To5zShODRFphIeK0G43o9m0l7kNujFmx2zWUb8hoOzDtJnLzFOFIKHhaRAUN6t2MDAbolvxPl820TuCJtXUt6WIAgxbgm9u/OOR/l+dAbIPKiJKVw+k2hhtZyBmJcg4JYTBYwx0en/BsyQD1qzceOKE5gOpLh36424QWIlJ4ZbSjv7ZYzQ+wCayYg87yds7jWFwN1P0Xd4Y2NdSmlA6920yVPq1xDAgIPhC2zoloc/9ZQNIkJLE1S1W23UETru3kKeeGMRUBOQpPL9axNmqawQp/NrT+Cs/pv7YPVfr9xRYTdaPwvyDujloOc2H+laZxOJUSLaxnAyItiuASrC9ZiytQ558EFfUxwQNdME+dEr6n7op9PSdWqsjbkZqx2E91c/c7cJiPtVzJKHIWhzr4PwkXq/EUF/LaK5Zl1ELn7uxcOHwKf8EtdaszMUehjzEsNP5Cmu/fUiJsY36nueY3oD65TJuOlouEaeckpHcc1Hs1INomurp07IAfW/LKZAucPELpNV3gIlMz2sRbOS2KiykvZlKfSyFUewefbiK7ITbChUgT829p44KyvBnsvebQPJmjv4stnIqPRipgNoT9cefgiCb9fLFsIrFT1cJyG/vZJfzwya9zfU/wq9cEFM6EPFzeIfBskwttCIe/JnYoREhlM6miZFLvfNIGuZcBvys="
  on:
    tags: true
    repo: starofrainnight/install-qt-binding
    python: 3.6
